### PR TITLE
homepage updated to display messages

### PR DESCRIPTION
**Pull request by jonpillay**
Homepage working as an example

### CODE REVIEW

**Review by SamWhite745 — CHANGES_REQUESTED** [review]
Can you make some tests for these please!

**Comment by jonpillay** [comment]
Rspec is updated to reflect the behaviour. This pull request and then next :-)

**Comment by jonpillay** [comment]
I'm wondering. i made two pull requests quite quickly with minimal differences. I suppose I could just delete them and push a more comprehensive request(?)

**Comment by SamWhite745** [comment]
I only see the one PR?

**Comment by jonpillay** [comment]
Yeah I was wondering about that (one PR). As there a way to remove them and I'll create a new one that has all incorporated

**Pull request closed without merging**
